package main

import (
	"github.com/reiver/go-c80"
)

func init() {
	textWidth := c80.Terminal.Width()

	text := c80.Terminal.Runes()

	text[0]  = 'W'
	text[1]  = 'e'
	text[2]  = 'l'
	text[3]  = 'c'
	text[4]  = 'o'
	text[5]  = 'm'
	text[6]  = 'e'
	text[7]  = ' '
	text[8]  = 't'
	text[9]  = 'o'
	text[10] = ' '
	text[11] = 't'
	text[12] = 'h'
	text[13] = 'e'
	text[14] = ' '
	text[15] = 'c'
	text[16] = 'y'
	text[17] = 'b'
	text[18] = 'e'
	text[19] = 'r'
	text[20] = '8'
	text[21] = '0'
	text[22] = '!'

	text[2*textWidth+ 0] = 'm'
	text[2*textWidth+ 1] = 'a'
	text[2*textWidth+ 2] = 'g'
	text[2*textWidth+ 3] = 'i'
	text[2*textWidth+ 4] = 'c'
	text[2*textWidth+ 5] = '2'
	text[2*textWidth+ 6] = '5'
	text[2*textWidth+ 7] = '6'
	text[2*textWidth+ 8] = ' '
	text[2*textWidth+ 9] = 'v'
	text[2*textWidth+10] = '0'
	text[2*textWidth+11] = '.'
	text[2*textWidth+12] = '0'
	text[2*textWidth+13] = '.'
	text[2*textWidth+14] = '1'
	text[2*textWidth+15] = '.'
	text[2*textWidth+16] = '0'
	text[2*textWidth+17] = '0'
	text[2*textWidth+18] = '0'
	text[2*textWidth+19] = '0'

	text[4*textWidth+ 0] = 'P'
	text[4*textWidth+ 1] = 'o'
	text[4*textWidth+ 2] = 'w'
	text[4*textWidth+ 3] = 'e'
	text[4*textWidth+ 4] = 'r'
	text[4*textWidth+ 5] = 'e'
	text[4*textWidth+ 6] = 'd'
	text[4*textWidth+ 7] = ' '
	text[4*textWidth+ 8] = 'b'
	text[4*textWidth+ 9] = 'y'
	text[4*textWidth+10] = ' '
	text[4*textWidth+11] = 'd'
	text[4*textWidth+12] = 'o'
	text[4*textWidth+13] = 't'
	text[4*textWidth+14] = '-'
	text[4*textWidth+15] = 'm'
	text[4*textWidth+16] = 'a'
	text[4*textWidth+17] = 't'
	text[4*textWidth+18] = 'r'
	text[4*textWidth+19] = 'i'
	text[4*textWidth+20] = 'x'
	text[4*textWidth+21] = ' '
	text[4*textWidth+22] = 'g'
	text[4*textWidth+23] = 'r'
	text[4*textWidth+24] = 'a'
	text[4*textWidth+25] = 'p'
	text[4*textWidth+26] = 'h'
	text[4*textWidth+27] = 'i'
	text[4*textWidth+28] = 'c'
	text[4*textWidth+29] = 's'
	text[4*textWidth+30] = '.'

	text[6*textWidth+ 0] = 'H'
	text[6*textWidth+ 1] = 'e'
	text[6*textWidth+ 2] = 'l'
	text[6*textWidth+ 3] = 'l'
	text[6*textWidth+ 4] = 'o'
	text[6*textWidth+ 5] = ' '
	text[6*textWidth+ 6] = 'w'
	text[6*textWidth+ 7] = 'o'
	text[6*textWidth+ 8] = 'r'
	text[6*textWidth+ 9] = 'l'
	text[6*textWidth+10] = 'd'
	text[6*textWidth+11] = '!'

	text[8*textWidth+0] = 'R'
	text[8*textWidth+1] = 'E'
	text[8*textWidth+2] = 'A'
	text[8*textWidth+3] = 'D'
	text[8*textWidth+4] = 'Y'
}
